port = 8080

[metadata]
amiId = "ami-123456789"
localHostname = "ip-10-251-50-12.ec2.internal"
productCodes = "asdf\n1234"
publicHostname = "ec2-203-0-113-25.compute-1.amazonaws.com"
publicIpV4 = "10.251.50.12"
reservationId = "r-fea54097"
